// NolimitCode models - generated by the NolimitCode cloud, no user API key

window.NOLIMIT_MODELS = [
  { id: 'free/mimo-v2.6-flash-free', zenId: 'mimo-v2.6-flash-free', label: 'NolimitCoder Pro', provider: 'mimo', category: 'FLASH', context: '1M', free: true, endpoint: 'chat', desc: 'NolimitCoder Pro' },
];

window.MODEL_CATEGORIES = ['ALL','FREE'];
