// NolimitCode models - generated by the NolimitCode cloud, no user API key

window.NOLIMIT_MODELS = [
  { id: 'free/nolimitcoder-v3', zenId: 'muse-spark-1.3-contributor-free', label: 'NolimitCoderV3', provider: 'nolimit', category: 'FREE', context: '256k', free: true, endpoint: 'responses', desc: 'Newest NolimitCode model' },
  { id: 'free/nolimitcoder-v2', zenId: 'muse-spark-1.2-contributor-free', label: 'NolimitCoderV2', provider: 'nolimit', category: 'FREE', context: '256k', free: true, endpoint: 'responses', desc: 'NolimitCode model' },
];

window.MODEL_CATEGORIES = ['ALL','FREE'];
