// NolimitCode models - generated by the NolimitCode cloud, no user API key

window.NOLIMIT_MODELS = [
  { id: 'free/space-bunny-free', zenId: 'space-bunny-free', label: 'NolimitCoder 1.0 Flash', provider: 'space-bunny', category: 'FLASH', context: '1M', free: true, endpoint: 'chat', desc: 'NolimitCoder 1.0 Flash' },
];

window.MODEL_CATEGORIES = ['ALL','FREE'];
