const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getStore: () => ipcRenderer.invoke('store:get'),
  setStore: (data) => ipcRenderer.invoke('store:set', data),
  authStatus: () => ipcRenderer.invoke('auth:status'),
  authLogin: () => ipcRenderer.invoke('auth:login'),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  onAuthChanged: (cb) => ipcRenderer.on('auth:changed', (_, p) => cb(p)),
  getVersion: () => ipcRenderer.invoke('app:version'),
  getPaths: () => ipcRenderer.invoke('app:paths'),
  fetchZenModels: (apiKey) => ipcRenderer.invoke('net:fetch-zen-models', apiKey),
  discoverLocal: () => ipcRenderer.invoke('net:discover-local'),
  chatStreamStart: (payload) => ipcRenderer.send('chat:stream-start', payload),
  chatStreamAbort: (payload) => ipcRenderer.send('chat:stream-abort', payload || {}),
  projectsDir: () => ipcRenderer.invoke('projects:dir'),
  projectList: () => ipcRenderer.invoke('projects:list'),
  projectCreate: (name) => ipcRenderer.invoke('projects:create', name),
  projectRename: (oldName, newName) => ipcRenderer.invoke('projects:rename', oldName, newName),
  projectRenamePath: (oldPath, newName) => ipcRenderer.invoke('projects:renamePath', oldPath, newName),
  projectDelete: (name) => ipcRenderer.invoke('projects:delete', name),
  projectPick: () => ipcRenderer.invoke('projects:pick'),
  fsBrowse: (path) => ipcRenderer.invoke('fs:browse', { path }),
  fsMkdir: (path, name) => ipcRenderer.invoke('fs:mkdir', { path, name }),
  projectFiles: (dirPath, includeContents, nonBlocking) => ipcRenderer.invoke('projects:files', dirPath, includeContents, nonBlocking),
  projectScanAsync: (dirPath) => ipcRenderer.invoke('projects:scanAsync', dirPath),
  openPath: (p) => ipcRenderer.invoke('projects:openPath', p),
  toolsExec: (data) => ipcRenderer.invoke('tools:exec', data),
  toolsCancel: (data) => ipcRenderer.invoke('tools:cancel', data || {}),
  saveImage: (data) => ipcRenderer.invoke('img:save', data),
  cancelDownload: (id) => ipcRenderer.invoke('tools:cancel-download', id),
  debugLog: (tag, data) => { try { ipcRenderer.send('log:debug', { tag, data }); } catch {} },
  logError: (tag, error, detail) => { try { ipcRenderer.send('log:error', { tag, error, detail }); } catch {} },
  errRead: () => ipcRenderer.invoke('errlog:read'),
  errPath: () => ipcRenderer.invoke('errlog:path'),
  errOpen: () => ipcRenderer.invoke('errlog:open'),
  errClear: () => ipcRenderer.invoke('errlog:clear'),
  knownFolders: () => ipcRenderer.invoke('sys:knownFolders'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  previewStart: (dirPath) => ipcRenderer.invoke('preview:start', dirPath),
  previewStop: (dirPath) => ipcRenderer.invoke('preview:stop', dirPath),
  previewWatch: (dirPath) => ipcRenderer.invoke('preview:watch', dirPath),
  previewUnwatch: (dirPath) => ipcRenderer.invoke('preview:unwatch', dirPath),
  onPreviewFileChanged: (cb) => ipcRenderer.on('preview:file-changed', (_, d) => cb(d)),
  videoExport: (data) => ipcRenderer.invoke('video:export', data),
  videoReveal: (filePath) => ipcRenderer.invoke('video:reveal', filePath),
  videoAbort: () => ipcRenderer.invoke('video:abort'),
  onVideoProgress: (cb) => ipcRenderer.on('video:progress', (_, d) => cb(d)),
  termRun: (data) => ipcRenderer.invoke('term:run', data),
  isAdmin: () => ipcRenderer.invoke('sys:isAdmin'),
  relaunchAdmin: () => ipcRenderer.invoke('app:relaunchAdmin'),
  helperState: () => ipcRenderer.invoke('sys:helperState'),
  proxyStatus: () => ipcRenderer.invoke('proxy:status'),
  proxyRefresh: () => ipcRenderer.invoke('proxy:refresh'),
  onProxyStatus: (cb) => ipcRenderer.on('proxy:status', (_, d) => cb(d)),

  // Chunky nesou ID streamu ({s, d}) — renderer je routuje do správného chatu,
  // takže dvě relace mohou generovat současně bez míchání odpovědí.
  // onError posílá payload NEZKRÁCENÝ, aby šlo routovat podle `s` (chyba je v `e`).
  onChunk: (cb) => ipcRenderer.on('chat:stream-chunk', (_, d) => cb(d)),
  onEnd: (cb) => ipcRenderer.on('chat:stream-end', (_, d) => cb(d || {})),
  onError: (cb) => ipcRenderer.on('chat:stream-error', (_, d) => cb(d || {})),
  onAppBlocked: (cb) => ipcRenderer.on('app:blocked', (_, d) => cb(d)),
  onAppUnblocked: (cb) => ipcRenderer.on('app:unblocked', (_, d) => cb(d || {})),
  startUpdate: (url) => ipcRenderer.invoke('app:update', url),
  onUpdateProgress: (cb) => ipcRenderer.on('app:update-progress', (_, d) => cb(d)),
  onDownload: (cb) => ipcRenderer.on('nlc-download', (_, p) => cb(p)),
  removeListeners: () => {
    ipcRenderer.removeAllListeners('chat:stream-chunk');
    ipcRenderer.removeAllListeners('chat:stream-end');
    ipcRenderer.removeAllListeners('chat:stream-error');
    ipcRenderer.removeAllListeners('nlc-download');
    ipcRenderer.removeAllListeners('auth:changed');
  }
});
